GET http://localhost:3002/events HTTP/1.1

###

POST http://localhost:3002/events HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTM2NDIyNywiZXhwIjoxNjQ5MzY3ODI3fQ.oHzPSHMqx5KwEtk2U9KZcfo4Ap8pwUJrw6zx0aj4GB8

{
    "title": "Event One",
    "datetime": "2022-04-07T17:30:00-04:00",
    "description": "A sample event."
}

###

PUT http://localhost:3002/events HTTP/1.1

###

DELETE http://localhost:3002/events HTTP/1.1

###

GET http://localhost:3002/events/624f37ea3bfffe2d2cba0a08 HTTP/1.1

###

POST http://localhost:3002/events/624f37ea3bfffe2d2cba0a08 HTTP/1.1

###

PUT http://localhost:3002/events/624f37ea3bfffe2d2cba0a08 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTM2NDIyNywiZXhwIjoxNjQ5MzY3ODI3fQ.oHzPSHMqx5KwEtk2U9KZcfo4Ap8pwUJrw6zx0aj4GB8

{
    "title": "Event One",
    "datetime": "2022-04-07T18:30:00-04:00",
    "description": "A sample event, now updated."
}

###

DELETE http://localhost:3002/events/624f37ea3bfffe2d2cba0a08 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTM2NDIyNywiZXhwIjoxNjQ5MzY3ODI3fQ.oHzPSHMqx5KwEtk2U9KZcfo4Ap8pwUJrw6zx0aj4GB8
