GET http://localhost:3002/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTI3OTUyNywiZXhwIjoxNjQ5MjgzMTI3fQ.j03nQgYWfGWOjbh29MD4hVw6zvM4FRJLF-h0StGq6NU
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTIyOTMwNCwiZXhwIjoxNjQ5MjMyOTA0fQ.3YEqfVebCh1bS_K0GCQ3JbDuEbZpQxt4x4SsTHHw_t4

###

POST http://localhost:3002/users HTTP/1.1
Content-Type: application/json

{
    "email": "my-email@example.net",
    "firstName": "Ebidaj",
    "lastName": "Paleu",
    "password": "very-secret-password"
}

###

POST http://localhost:3002/users HTTP/1.1
Content-Type: application/json

{
    "email": "admin@example.net",
    "firstName": "Admin",
    "lastName": "Istrator",
    "password": "secretest-password"
}

###

PUT http://localhost:3002/users HTTP/1.1

###

DELETE http://localhost:3002/users HTTP/1.1

###

GET http://localhost:3002/users/624d34ac023215e067762c00 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQyYjUyM2I2N2RjNTg2YTE0N2Q0NCIsImlhdCI6MTY0OTIyOTIyNiwiZXhwIjoxNjQ5MjMyODI2fQ.jogB9iIu7flgDNwL2hY4AGzNVlV6Orm1k95py6uuxW8
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTIyOTMwNCwiZXhwIjoxNjQ5MjMyOTA0fQ.3YEqfVebCh1bS_K0GCQ3JbDuEbZpQxt4x4SsTHHw_t4

###

GET http://localhost:3002/users/624d2b523b67dc586a147d44 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQyYjUyM2I2N2RjNTg2YTE0N2Q0NCIsImlhdCI6MTY0OTIyOTIyNiwiZXhwIjoxNjQ5MjMyODI2fQ.jogB9iIu7flgDNwL2hY4AGzNVlV6Orm1k95py6uuxW8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTIyOTMwNCwiZXhwIjoxNjQ5MjMyOTA0fQ.3YEqfVebCh1bS_K0GCQ3JbDuEbZpQxt4x4SsTHHw_t4

###

POST http://localhost:3002/users/624cd2196a1407212bec7582 HTTP/1.1

###

PUT http://localhost:3002/users/624cd2196a1407212bec7582 HTTP/1.1

###

DELETE http://localhost:3002/users/624cd2196a1407212bec7582 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGNkMjE5NmExNDA3MjEyYmVjNzU4MiIsImlhdCI6MTY0OTIyNDMzNCwiZXhwIjoxNjQ5MjI3OTM0fQ.vRLrwXM0zML37N7c868b-e-ln0gGgEkIvqi81Ld9wNw
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQyYjUyM2I2N2RjNTg2YTE0N2Q0NCIsImlhdCI6MTY0OTIyOTIyNiwiZXhwIjoxNjQ5MjMyODI2fQ.jogB9iIu7flgDNwL2hY4AGzNVlV6Orm1k95py6uuxW8

###

DELETE http://localhost:3002/users/624d2b523b67dc586a147d44 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQyYjUyM2I2N2RjNTg2YTE0N2Q0NCIsImlhdCI6MTY0OTIyOTIyNiwiZXhwIjoxNjQ5MjMyODI2fQ.jogB9iIu7flgDNwL2hY4AGzNVlV6Orm1k95py6uuxW8

###

GET http://localhost:3002/users/624d34ac023215e067762c00/savedPayments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTI5MjQzNSwiZXhwIjoxNjQ5Mjk2MDM1fQ._4tFtniNzZ98a6YmKrUksWBoSTpZlREZzNw9MGCOyVU

###

POST http://localhost:3002/users/624d34ac023215e067762c00/savedPayments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTI5MjQzNSwiZXhwIjoxNjQ5Mjk2MDM1fQ._4tFtniNzZ98a6YmKrUksWBoSTpZlREZzNw9MGCOyVU

{
  "cardNumber": "1234-5678-8765-4321",
  "securityCode": "123",
  "billingName": "Ebidaj Paleu",
  "streetAddress": "123 Street Road",
  "city": "Citypolis",
  "state": "ST",
  "zipCode": "12345"
}

###

PUT http://localhost:3002/users/624d34ac023215e067762c00/savedPayments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTI5MjQzNSwiZXhwIjoxNjQ5Mjk2MDM1fQ._4tFtniNzZ98a6YmKrUksWBoSTpZlREZzNw9MGCOyVU

###

DELETE http://localhost:3002/users/624d34ac023215e067762c00/savedPayments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTI5MjQzNSwiZXhwIjoxNjQ5Mjk2MDM1fQ._4tFtniNzZ98a6YmKrUksWBoSTpZlREZzNw9MGCOyVU

###

GET http://localhost:3002/users/624d34ac023215e067762c00/savedPayments/624e03bf94fc037e048e5c65 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTI5MjQzNSwiZXhwIjoxNjQ5Mjk2MDM1fQ._4tFtniNzZ98a6YmKrUksWBoSTpZlREZzNw9MGCOyVU

###

POST http://localhost:3002/users/624d34ac023215e067762c00/savedPayments/624e03bf94fc037e048e5c65 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTI5MjQzNSwiZXhwIjoxNjQ5Mjk2MDM1fQ._4tFtniNzZ98a6YmKrUksWBoSTpZlREZzNw9MGCOyVU

###

PUT http://localhost:3002/users/624d34ac023215e067762c00/savedPayments/624e03bf94fc037e048e5c65 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTI5MjQzNSwiZXhwIjoxNjQ5Mjk2MDM1fQ._4tFtniNzZ98a6YmKrUksWBoSTpZlREZzNw9MGCOyVU

{
  "cardNumber": "1234-5678-8765-1111",
  "securityCode": "123",
  "billingName": "Ebidaj Paleu",
  "streetAddress": "123 Street Road",
  "city": "Citypolis",
  "state": "ST",
  "zipCode": "12345"
}

###

DELETE http://localhost:3002/users/624d34ac023215e067762c00/savedPayments/624e03bf94fc037e048e5c65 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTI5MjQzNSwiZXhwIjoxNjQ5Mjk2MDM1fQ._4tFtniNzZ98a6YmKrUksWBoSTpZlREZzNw9MGCOyVU

###

GET http://localhost:3002/users/624d34ac023215e067762c00/savedOrders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTMwMDI5MSwiZXhwIjoxNjQ5MzAzODkxfQ.mOmiggFjxYTOgF5Vp9L_cwBoj0ZLRWuTLLT1A2Os56s

###

POST http://localhost:3002/users/624d34ac023215e067762c00/savedOrders HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTMwMDI5MSwiZXhwIjoxNjQ5MzAzODkxfQ.mOmiggFjxYTOgF5Vp9L_cwBoj0ZLRWuTLLT1A2Os56s

{
    "name": "Sample saved order",
    "orderList": [
        {
            "menuItem": "624b5eac576d34717d67e8a1",
            "selectedOptions": {
                "Milk type": "Macadamia milk"
            }
        },
        {
            "menuItem": "624b5eac576d34717d67e8a6"
        },
        {
            "menuItem": "624b5eac576d34717d67e8a4"
        }
    ]
}

###

PUT http://localhost:3002/users/624d34ac023215e067762c00/savedOrders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTMwMDI5MSwiZXhwIjoxNjQ5MzAzODkxfQ.mOmiggFjxYTOgF5Vp9L_cwBoj0ZLRWuTLLT1A2Os56s

###

DELETE http://localhost:3002/users/624d34ac023215e067762c00/savedOrders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTMwMDI5MSwiZXhwIjoxNjQ5MzAzODkxfQ.mOmiggFjxYTOgF5Vp9L_cwBoj0ZLRWuTLLT1A2Os56s

###

GET http://localhost:3002/users/624d34ac023215e067762c00/savedOrders/624e52d08e3c3e3b299d1a0a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTMwMDI5MSwiZXhwIjoxNjQ5MzAzODkxfQ.mOmiggFjxYTOgF5Vp9L_cwBoj0ZLRWuTLLT1A2Os56s

###

POST http://localhost:3002/users/624d34ac023215e067762c00/savedOrders/624e52d08e3c3e3b299d1a0a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzZmVlNzUyNDRjYWNjMzA1NzQxYiIsImlhdCI6MTY0OTI5MjQzNSwiZXhwIjoxNjQ5Mjk2MDM1fQ._4tFtniNzZ98a6YmKrUksWBoSTpZlREZzNw9MGCOyVU

###

PUT http://localhost:3002/users/624d34ac023215e067762c00/savedOrders/624e52d08e3c3e3b299d1a0a HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTMwMDI5MSwiZXhwIjoxNjQ5MzAzODkxfQ.mOmiggFjxYTOgF5Vp9L_cwBoj0ZLRWuTLLT1A2Os56s

{
    "name": "Another sample saved order",
    "orderList": [
        {
            "menuItem": "624b5eac576d34717d67e8a1",
            "selectedOptions": {
                "Milk type": "Macadamia milk"
            }
        },
        {
            "menuItem": "624b5eac576d34717d67e8a6"
        },
        {
            "menuItem": "624b5eac576d34717d67e8a4"
        }
    ]
}

###

DELETE http://localhost:3002/users/624d34ac023215e067762c00/savedOrders/624e52d08e3c3e3b299d1a0a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTMwMDI5MSwiZXhwIjoxNjQ5MzAzODkxfQ.mOmiggFjxYTOgF5Vp9L_cwBoj0ZLRWuTLLT1A2Os56s
