GET http://localhost:3002/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQyYjUyM2I2N2RjNTg2YTE0N2Q0NCIsImlhdCI6MTY0OTIyOTIyNiwiZXhwIjoxNjQ5MjMyODI2fQ.jogB9iIu7flgDNwL2hY4AGzNVlV6Orm1k95py6uuxW8
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTIyOTMwNCwiZXhwIjoxNjQ5MjMyOTA0fQ.3YEqfVebCh1bS_K0GCQ3JbDuEbZpQxt4x4SsTHHw_t4

###

POST http://localhost:3002/users HTTP/1.1
Content-Type: application/json

{
    "email": "my-email@example.net",
    "firstName": "Ebidaj",
    "lastName": "Paleu",
    "password": "very-secret-password"
}

###

POST http://localhost:3002/users HTTP/1.1
Content-Type: application/json

{
    "email": "admin@example.net",
    "firstName": "Admin",
    "lastName": "Istrator",
    "password": "secretest-password"
}

###

PUT http://localhost:3002/users HTTP/1.1

###

DELETE http://localhost:3002/users HTTP/1.1

###

GET http://localhost:3002/users/624d34ac023215e067762c00 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQyYjUyM2I2N2RjNTg2YTE0N2Q0NCIsImlhdCI6MTY0OTIyOTIyNiwiZXhwIjoxNjQ5MjMyODI2fQ.jogB9iIu7flgDNwL2hY4AGzNVlV6Orm1k95py6uuxW8
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTIyOTMwNCwiZXhwIjoxNjQ5MjMyOTA0fQ.3YEqfVebCh1bS_K0GCQ3JbDuEbZpQxt4x4SsTHHw_t4

###

GET http://localhost:3002/users/624d2b523b67dc586a147d44 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQyYjUyM2I2N2RjNTg2YTE0N2Q0NCIsImlhdCI6MTY0OTIyOTIyNiwiZXhwIjoxNjQ5MjMyODI2fQ.jogB9iIu7flgDNwL2hY4AGzNVlV6Orm1k95py6uuxW8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQzNGFjMDIzMjE1ZTA2Nzc2MmMwMCIsImlhdCI6MTY0OTIyOTMwNCwiZXhwIjoxNjQ5MjMyOTA0fQ.3YEqfVebCh1bS_K0GCQ3JbDuEbZpQxt4x4SsTHHw_t4

###

POST http://localhost:3002/users/624cd2196a1407212bec7582 HTTP/1.1

###

PUT http://localhost:3002/users/624cd2196a1407212bec7582 HTTP/1.1

###

DELETE http://localhost:3002/users/624cd2196a1407212bec7582 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGNkMjE5NmExNDA3MjEyYmVjNzU4MiIsImlhdCI6MTY0OTIyNDMzNCwiZXhwIjoxNjQ5MjI3OTM0fQ.vRLrwXM0zML37N7c868b-e-ln0gGgEkIvqi81Ld9wNw
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQyYjUyM2I2N2RjNTg2YTE0N2Q0NCIsImlhdCI6MTY0OTIyOTIyNiwiZXhwIjoxNjQ5MjMyODI2fQ.jogB9iIu7flgDNwL2hY4AGzNVlV6Orm1k95py6uuxW8

###

DELETE http://localhost:3002/users/624d2b523b67dc586a147d44 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNGQyYjUyM2I2N2RjNTg2YTE0N2Q0NCIsImlhdCI6MTY0OTIyOTIyNiwiZXhwIjoxNjQ5MjMyODI2fQ.jogB9iIu7flgDNwL2hY4AGzNVlV6Orm1k95py6uuxW8
